/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kashy
 */
public class NewJFrame6 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame6
     */
    public NewJFrame6() {
        initComponents();
        setSize(900, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel1.setText("BANK  OF  INDORE... :-)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(53, 43, 461, 59);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setText("BANKING ISSUES ..... NO PROBLEM!!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(261, 108, 361, 28);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setText("ENTER NEW PIN-:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(53, 230, 234, 37);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setText("RE-ENTER NEW PIN-:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(53, 277, 234, 37);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setText("ENTER OLD PIN-:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(53, 183, 234, 37);

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(291, 230, 205, 37);

        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(291, 183, 205, 37);

        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(291, 277, 205, 37);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton1.setText("CHANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(184, 350, 152, 37);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/graphicstock-white-piggy-bank-isolated-on-blue-background_HYdxD3IbGOZ_SB_PM.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 900, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        try {
            Connector();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame6.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame6.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
private void Connector() throws ClassNotFoundException, SQLException {
         String S1=jTextField2.getText();
       String S2=jTextField1.getText();
       String S3=jTextField3.getText();
       int I1=Integer.parseInt(S2);
       int I2=Integer.parseInt(NewJFrame2.ss);
        int p=0;
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "Sanjeet", "ksanjeet");
            String sql="select * from customerdata";
        Statement st=con.createStatement();
                   ResultSet rs=st.executeQuery(sql);
               
                   
                  while(rs.next())
        {
            if(NewJFrame2.ss.equalsIgnoreCase(rs.getString(1)))
            {
               if(S1.equalsIgnoreCase(rs.getString(5)))
               {
                   if(S2.equalsIgnoreCase(S3))
                   {
                       String sql2="update customerdata set Pin=? WHERE AccNo=?";
                       PreparedStatement ps=con.prepareStatement(sql2);
                       ps.setInt(1,I1 );
                       ps.setInt(2, I2);
                       int j=ps.executeUpdate();
                   }
               }
            }
        }
               new NewJFrame11().setVisible(true);    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
