/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kashy
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    public NewJFrame4() {
        initComponents();
        setSize(900, 500);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel1.setText("BANK  OF  INDORE... :-)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(53, 43, 461, 59);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setText("BANKING ISSUES ..... NO PROBLEM!!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(261, 108, 361, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Enter Amount-->");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(61, 191, 190, 75);

        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(269, 215, 238, 27);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("WITHDRAW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(182, 276, 173, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/graphicstock-white-piggy-bank-isolated-on-blue-background_HYdxD3IbGOZ_SB_PM.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 900, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connector();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */private void Connector() throws ClassNotFoundException, SQLException {
        String S1 = jTextField1.getText();
        int p=0;
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "Sanjeet", "ksanjeet");
            String sql="select * from customerdata";
        Statement st=con.createStatement();
                   ResultSet rs=st.executeQuery(sql);
                   while(rs.next())
                   {
                       if(NewJFrame2.ss.equalsIgnoreCase(rs.getString(1)))
                       {
                           int i=Integer.parseInt(rs.getString(4));
                           int a=Integer.parseInt(S1);
                            int I2=Integer.parseInt(NewJFrame2.ss);
                           i=i-a;
                           String sql2="update customerdata set Bal=? WHERE AccNo=?";
                       PreparedStatement ps=con.prepareStatement(sql2);
                       ps.setInt(1,i);
                       ps.setInt(2,I2);
                       int j=ps.executeUpdate();
                       }
                   }
            String sql3="select * from ATMData";
            ResultSet rs1=st.executeQuery(sql3);
            while(rs1.next())
            {
                int q=Integer.parseInt(rs1.getString(1));
                int b=Integer.parseInt(S1);
                q=q-b;
                int t=1;
                 String sql4="update ATMData set cash=? WHERE num=?";
                       PreparedStatement ps=con.prepareStatement(sql4);
                       ps.setInt(1,q);
                       ps.setInt(2,t);
                int j=ps.executeUpdate();
            }
             new NewJFrame11().setVisible(true);
     }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
