/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kashy
 */
public class NewJFrame12 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame12
     */
    public NewJFrame12() {
        initComponents();
        setSize(900, 500);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel1.setText("BANK  OF  INDORE... :-)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 33, 461, 59);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setText("BANKING ISSUES ..... NO PROBLEM!!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 70, 361, 28);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setText("Enter Account Number-:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 254, 39);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setText("Enter Name-:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 254, 39);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel6.setText("Enter CIF Number-:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 230, 254, 39);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel7.setText("Enter Balance-:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 254, 39);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel8.setText("Enter Pin-:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 330, 254, 39);

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 130, 221, 39);

        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 230, 221, 39);

        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(280, 280, 221, 39);

        jTextField4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(280, 330, 221, 39);

        jTextField5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(280, 180, 221, 39);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 170, 163, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/graphicstock-white-piggy-bank-isolated-on-blue-background_HYdxD3IbGOZ_SB_PM.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            Connector();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Connector() throws ClassNotFoundException, SQLException {
        String S1 = jTextField1.getText();
        String S2 = jTextField5.getText();
        String S3 = jTextField2.getText();
        String S4 = jTextField3.getText();
        String S5 = jTextField4.getText();
        int p=0;
        int I1=Integer.parseInt(S1);
        int I2=Integer.parseInt(S3);
        int I3=Integer.parseInt(S4);
        int I4=Integer.parseInt(S5);
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "Sanjeet", "ksanjeet");
            String sql="select * from customerdata";
        Statement st=con.createStatement();
                   ResultSet rs=st.executeQuery(sql);
                   String sql2="insert into customerdata values(?,?,?,?,?)";
                    PreparedStatement ps=con.prepareStatement(sql2);
                       ps.setInt(1,I1);
                       ps.setString(2, S2);
                       ps.setInt(3,I2);
                       ps.setInt(4,I3);
                       ps.setInt(5,I4);
                       int j=ps.executeUpdate();
                   new NewJFrame13().setVisible(true);
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
