/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kashy
 */
public class NewJFrame14 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame14
     */
    public NewJFrame14() {
        initComponents();
        setSize(900, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel1.setText("BANK  OF  INDORE... :-)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 33, 461, 59);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setText("BANKING ISSUES ..... NO PROBLEM!!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 70, 361, 28);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setText("Enter Amount-:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 218, 180, 54);

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(246, 232, 271, 27);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton1.setText("ReFill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(134, 304, 245, 34);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/graphicstock-white-piggy-bank-isolated-on-blue-background_HYdxD3IbGOZ_SB_PM.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 3, 900, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connector();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame14.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame14.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  private void Connector() throws ClassNotFoundException, SQLException {
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "Sanjeet", "ksanjeet");
            String sql="select * from ATMData";
        Statement st=con.createStatement();
                   ResultSet rs=st.executeQuery(sql);
                    while(rs.next())
        {
          int I1=Integer.parseInt(rs.getString(1));
          String S1=jTextField1.getText();
          int I2=Integer.parseInt(S1);
          I2=I1+I2;
          String sql2="update ATMData set cash=? WHERE num=?";
                       PreparedStatement ps=con.prepareStatement(sql2);
                       ps.setInt(1,I2);
                       ps.setInt(2,1);
                       int j=ps.executeUpdate();
        }
                    new NewJFrame13().setVisible(true);
             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
